language: node_js
services:
  - mongodb
node_js:
  - "12"
cache:
  directories:
  - "node_modules"
env:
  global:
    - CC_TEST_REPORTER_ID=9f1173797b3aca65254ee1d50b06d0ad27f81eeeb9db3b0567ece66eefbb1b9f
    - NODE_ENV=test
    - PORT=9000
    - LOGGER_TYPE=console
    - HOST_IP=127.0.0.1
    - DEBUG=redis-cache-plugin
    - NODE_PATH=app/src
    - EXEC_MIGRATION=true
    - JWT_SECRET=mysecret
    - COOKIE_DOMAIN=mymachine
    - SESSION_KEY=test
    - PUBLIC_URL=http://localhost:9000
    - API_VERSION=v1
    - CT_REGISTER_MODE=auto
    - SPARKPOST_KEY=fakeSparkpostKey
    - FASTLY_APIKEY=foo
    - FASTLY_SERVICEID=bar
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn test
  - yarn run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
