language: node_js
services:
  - mongodb
node_js:
  - "12.6"
  - "12"
cache:
  directories:
  - "node_modules"
env:
  global:
    - CC_TEST_REPORTER_ID=cbef27efebac45f676a4a44ac1cc1257d32178cd2858f9bc66678a7ab35996fb
    - NODE_ENV=test
    - PORT=9000
    - LOGGER_TYPE=console
    - DEBUG=redis-cache-plugin
    - NODE_PATH=app/src
    - EXEC_MIGRATION=true
    - JWT_SECRET=mysecret
    - COOKIE_DOMAIN=mymachine
    - SESSION_KEY=test
    - PUBLIC_URL=http://localhost:9000
    - SPARKPOST_KEY=fakeSparkpostKey
    - FASTLY_APIKEY=foo
    - FASTLY_SERVICEID=bar
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
