version: "3"
services:
  develop:
    build: .
    ports:
      - "9000:9000"
    container_name: control-tower
    env_file:
      - dev.env
    environment:
      NODE_ENV: test
      SESSION_KEY: test
    command: test
    depends_on:
      - mongo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo
    container_name: control-tower-mongo
    command: --smallfiles
    ports:
      - "27017"
    restart: always
