apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  template:
    metadata:
      labels:
        name: {name}
    spec:
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "gateway"
          effect: "NoSchedule"
      containers:
        - name: {name}
          image: vizzuality/{name}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "1Gi"
          args:
            - start
          env:
            - name: PORT
              value: "9000"
            - name: LOGGER_TYPE
              value: console
            - name: NODE_ENV
              value: prod
            - name: NODE_PATH
              value: app/src
            - name: BASICAUTH_USERNAME
              value: vizzuality
            - name: CONFIRM_URL_REDIRECT
              value: http://api.skydipper.com
            - name: PUBLIC_URL
              value: http://api.skydipper.com
            - name: FROM_NAME
              value: "admin@skydipper.com"
            - name: APP_NAME
              value: "Skydipper API"
            - name: APP_LOGO
              value: https://skydipper.com/images/logo.png
            - name: APP_COLOR
              value: "#f1b319"
            - name: CT_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: CT_MONGO_URI
            - name: SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: SESSION_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: JWT_SECRET
            - name: BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: BASICAUTH_PASSWORD
            - name: SPARKPOST_KEY
              valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: SPARKPOST_KEY

          ports:
            - containerPort: 9000
      restartPolicy: Always
