apiVersion: v1
kind: Service
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000
  selector:
    name: {name}
